### ISSUE TITLE
Revive this project/repo

### ISSUE THREAD

**Issue by Xenokrates** [NoeSamaille/node-red-contrib-activedirectory#13]
Dear @NoeSamaille,
it seems that you have abbandoned this project/repo.
What a pitty.

There are 3 open pull requests, which can be easily integrated with one `CLICK`.
No reaction to issues and PRs.
Currently it is just another corpse of a NodeRed node, because the error handling is not working and there is no way to catch the error and keep the flows reacting. (See th PRs.)
What a pitty, because the basic functions are very usable in NR flows.

So, how do you see future of the project ?
- Are you willing to react and accept PRs to keep the nodes living ?
- Would it be an option to transfer repo ownership, so that it is possible to debug the nodes and keep the nodes living ? 
- Could you please add a LICENSE, so that at least others can build on your work with acknowlegement of you work ?

Best regards
Xenokrates

**Comment by NoeSamaille** [comment]
Hi @Xenokrates, 

You are absolutely right, that's a pity this project is dead for quite some time now, and unfortunately, I don't have the time to maintain it, at all.

To answer your questions, I'd be more than happy to welcome anyone who wants to contribute as a collaborator.
Just put this under MIT license as well.

Thanks for waking me up ;) 

All the best

**Comment by Xenokrates** [comment]
Dear @NoeSamaille,

thank you for your positive reply.
Yes ,time is a spare item nowadays.
I hope it's possible to keep this project living without using much of your time.

Thank you and best regards

**Comment by Xenokrates** [comment]
Hi @NoeSamaille ,
would you also like to give me access to publish new packages at NPM ?
I opened a new account at [npmjs.com](https://www.npmjs.com/~xenokrates) for it.
After solving other open issues, it would be nice to push a new version 0.2.0 to NPM.

Best regards

**Comment by NoeSamaille** [comment]
@Xenokrates done, you need to set up 2FA to publish.

Is it ok to close the issue?

**Comment by Xenokrates** [comment]
I will activate 2FA.
Thank you.
