### ISSUE TITLE
Some suggestions - add config node

### ISSUE THREAD

**Issue by PaulWieland** [NoeSamaille/node-red-contrib-activedirectory#7]
This node is a good start, but it really should have a config node to store the connection parameters so that they don't have to be rewritten with every single node added to the pallet.

It would also be nice if the find user node had a list of checkboxes in its config to allow you to easily select which attributes to return (overidable by passing in the `ad_attributes` array).

And speaking of `ad_attributes` - the `find user` node's information window doesn't mention it - I found it on GitHub.

**Comment by Xenokrates** [comment]
Hi @PaulWieland
it is a good suggestion to implement a config node for all server settings.

About the checkboxes for the `ad_attributes` array I think some hint in the docu is a first step.
There are so many attributes in AD that can be fetched with a setting in `ad_attributes`.
Finally the default attributes are just a small subset of them.
I think it would be fine to change/set the `ad_attributes` as a JSON aaray in the config node. 
(Overwritable by the msg.)

Best regards

**Comment by PaulWieland** [comment]
@Xenokrates For the checkbox idea, it was simply to provide an easy way to get the most common attributes. They could also just be listed in the node info as a handy reference.
